
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User_Len
 */
public class miniPHP extends javax.swing.JFrame {

    /**
     * Creates new form miniPHP
     */
    public miniPHP() {
        initComponents();
    }
    //Variables
    Yylex objYylex;
    String Ruta;
    Boolean bandera;
    //Cargar archivo PHP
    private void cargarPHP(Component a) throws FileNotFoundException, IOException
    {
     JFileChooser dialog = new JFileChooser();
     FileNameExtensionFilter filter = new FileNameExtensionFilter("archivos php", "php");
     dialog.setFileFilter(filter);
     if(dialog.showOpenDialog(a) == JFileChooser.APPROVE_OPTION)
     {
         try{
             File selectedFile = dialog.getSelectedFile();
             Ruta = selectedFile.getPath();
             FileReader objFileReader = new FileReader(Ruta);
             BufferedReader objBufferedReader = new BufferedReader(objFileReader);
             objYylex = new Yylex(objFileReader);
             objYylex.nextToken();
         }catch(NumberFormatException e){}
     }
    }
    //Cargar un archivo JFlex
    private void cargarJFLEX(Component a)
    {
     JFileChooser dialog = new JFileChooser();
     FileNameExtensionFilter filter = new FileNameExtensionFilter("archivos jflex", "flex");
     dialog.setFileFilter(filter);
     if(dialog.showOpenDialog(a) == JFileChooser.APPROVE_OPTION)
     {
         File selectedFile = dialog.getSelectedFile();
         jflex.Main.main(new String[] {selectedFile.getPath()});
     }
    }
    private void archivoSalida(Component a) throws FileNotFoundException, IOException{
        Ruta = Ruta.substring(0,Ruta.length()-3);
        File salida = new File(Ruta + "out");
        RandomAccessFile raf = new RandomAccessFile(salida,"rw");
        bandera = Boolean.parseBoolean(objYylex.Cola.poll().toString());
        int contador = objYylex.Cola.size();
        if(bandera){
            for (int i = 0; i < contador; i++) {
               raf.writeBytes(objYylex.Cola.poll().toString());
            }
        }else{
            raf.writeBytes("Se encontró un error en la linea " + objYylex.Cola.poll().toString());
        }
        raf.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnFlex = new javax.swing.JButton();
        jbtnPHP = new javax.swing.JButton();
        jbtnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnFlex.setText("jFlex");
        jbtnFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFlexActionPerformed(evt);
            }
        });

        jbtnPHP.setText("jPHP");
        jbtnPHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPHPActionPerformed(evt);
            }
        });

        jbtnGo.setText("jButton1");
        jbtnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnGo)
                    .addComponent(jbtnPHP)
                    .addComponent(jbtnFlex))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbtnFlex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGo)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPHPActionPerformed
        try {
            cargarPHP(this);
        } catch (IOException ex) {
            Logger.getLogger(miniPHP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbtnPHPActionPerformed

    private void jbtnFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFlexActionPerformed
        // TODO add your handling code here:
        cargarJFLEX(this);
    }//GEN-LAST:event_jbtnFlexActionPerformed

    private void jbtnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGoActionPerformed
        try {
            // TODO add your handling code here:
            archivoSalida(this);
        } catch (IOException ex) {
            Logger.getLogger(miniPHP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miniPHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miniPHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miniPHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miniPHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miniPHP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnFlex;
    private javax.swing.JButton jbtnGo;
    private javax.swing.JButton jbtnPHP;
    // End of variables declaration//GEN-END:variables
}
